### ISSUE TITLE
UP.py Unable to run it properly

### ISSUE THREAD

**Issue by JesConsuegra** [lkoepsel/AVR_FF#1]
I'm new to flashforth. I've trying to use different serial terminal programs without success. Most of them overrun the interpreter when loading forth definitions from a file. UP.py was a nice discovery and I was hopeful in having a solution for uploading forth definitions to my AVR boards. I don't know Python, so I blindly followed the nice instructions for the linux environment found here and ended with an UP.py that seemed to work when launched. But it always gives me an error at line 138 telling 

........./up.py", line 138 in main
    config.port = values['port']
KeyError: 'port'

In the documentation I can read;

A .env file is required at the parent level *./AVR_FF* for the port, with *port* defined. An example is:

port=/dev/cu.usbmodem1401

I am not really sure that this can be related to the problem. 
If it is, how to set the .env filename should be told in the docs.

I cannot proceed further. Any help will be very welcome.
Thanks in advance.

**Comment by lkoepsel** [comment]
Thank you for your question, clearly I need to make it be more understandable.

The python program up.py will read the _.env_ file to get the port definition. In the example, the definition is _/dev/cu.usbmodem1401_. As you are in Linux, the port definitions will typically be  _/dev/ttyACM0_ or perhaps _/dev/ttyUSB0_.

Once the port has been properly identified in the file, the _.env_ file itself needs to reside in the current folder in the terminal. For example, I typically open a terminal and run in the AVR_FF folder and the _.env_ file resides at that level.

I have recently started having issues with the latest version of FF and _up.py_, I'm not sure what is the issue. I'll advise here when I have it figured out.

**Comment by lkoepsel** [comment]
I also suggest you consider ff-shell.py from FlashForth. I wrote up.py because ff-shell.py was only for Python 2.7, the new version works well under Python3. It doesn't have the issues with uploading large files which up.py currently has. 

Let me know if you continue to have issues.

**Comment by lkoepsel** [comment]
I made some changes to _up.py_ today:
1. Added automatic removal of comments, both as separate lines and in-line to simplify and accelerate uploading. Previously seen errors have disappeared.
2. Program will wait for a ready response _'ok<#,ram> \r\n'_ prior to uploading, this too seems to have helped reduce upload errors.
3. Changed _-e_ or _--empty_ flags to mean "send an empty command, prior to upload". I use this when I'm sending my initial HAL file as I know I want the HAL file to be the first user file on the chip.
To use: _up.py -e Library/328P_HAL.fs_

**Comment by JesConsuegra** [comment]
> Thank you for your question, clearly I need to make it be more understandable.
> 
> The python program up.py will read the _.env_ file to get the port definition. In the example, the definition is _/dev/cu.usbmodem1401_. As you are in Linux, the port definitions will typically be _/dev/ttyACM0_ or perhaps _/dev/ttyUSB0_.
> 
> Once the port has been properly identified in the file, the _.env_ file itself needs to reside in the current folder in the terminal. For example, I typically open a terminal and run in the AVR_FF folder and the _.env_ file resides at that level.
> 
> I have recently started having issues with the latest version of FF and _up.py_, I'm not sure what is the issue. I'll advise here when I have it figured out.

Thanks a lot for this quick answer,. So I understand the file has to be called just ". env" and be located at the AVR_FF folder. I'm so sorry, Maybe by years of using Windows ( not anymore) I misunderstood your statements and thought that ".env" was the suffix of some file, when it's clear that it's just the name. My apologies. 
  I've noticed you have uploaded a modified version, so I will try it with that one.

I did try the "ff-shell.py" from the FF site and it was as you say, running only in Python 2. I'll try to find that new version just to check if I have the last FF. 

Yes, the device is /dev/ttyACM0

Again many thanks for your help and for this nice program.

**Comment by lkoepsel** [comment]
A slight correction, I made a mistake earlier and called the file _env.make_, which is what I use in my C programs. For the _up.py_ program, it needs to be called _.env_ . I apologize for the confusion.

In your case the file _.env_ would contain one line:
`
port=/dev/ttyACM0
`

And the file needs to be in your current folder, that is, the one in which you are running _up.py_

**Comment by JesConsuegra** [comment]
It works now, thanks a lot!
